# Generated by Django 4.2.5 on 2023-09-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('appointment_no', models.CharField(max_length=255)),
                ('appointment_date', models.DateTimeField()),
                ('phone', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('doctor', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('priority', models.CharField(max_length=255)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Appointment Details',
                'verbose_name_plural': 'Appointment Details',
            },
        ),
    ]
