# Generated by Django 4.2.5 on 2023-09-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('specialist', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='specialist',
        ),
    ]
