# Generated by Django 4.2.5 on 2023-09-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_bed_bedgroup_bedtype_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpdPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bp', models.CharField(max_length=20)),
                ('pulse', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('respiration', models.IntegerField()),
                ('symptoms_type', models.CharField(max_length=255)),
                ('symptoms_title', models.CharField(max_length=255)),
                ('symptoms_description', models.CharField(max_length=255)),
                ('admission_date', models.DateTimeField()),
                ('is_case_casualty', models.BooleanField()),
                ('is_old_patient', models.BooleanField()),
                ('is_tpa', models.BooleanField()),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=255)),
                ('consultant_doctor', models.CharField(max_length=255)),
                ('bed_group', models.CharField(max_length=255)),
                ('bed_number', models.CharField(max_length=10)),
            ],
        ),
    ]
