# Generated by Django 4.2.5 on 2023-09-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_ipdpatient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symtopms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_type', models.CharField(max_length=255)),
                ('symptoms_title', models.CharField(max_length=255)),
                ('symptoms_description', models.CharField(max_length=255)),
            ],
        ),
    ]
