# Generated by Django 4.2.5 on 2023-09-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Med_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_category', models.CharField(max_length=100)),
            ],
        ),
    ]
