# Generated by Django 4.2.5 on 2023-09-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Med_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('dose', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
            ],
        ),
    ]
