# Generated by Django 4.2.5 on 2023-09-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_remove_med_details_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='med_details',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='med_details',
            name='interval',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
