# Generated by Django 4.2.5 on 2023-09-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('adminapp', '0018_donor_purchase_med'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total (Rs.)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount (%)')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount (Rs.)')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tax (Rs.)')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net Amount (Rs.)')),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash')], max_length=255, verbose_name='Payment Mode')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount (Rs.)')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
