# Generated by Django 4.2.5 on 2023-09-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_financialinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
