# Generated by Django 4.2.5 on 2023-09-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_alter_donor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor_det',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Donor Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('blood_group', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=10)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Father Name')),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact No')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total (Rs.)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount (%)')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount (Rs.)')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tax (Rs.)')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net Amount (Rs.)')),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash')], max_length=255, verbose_name='Payment Mode')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount (Rs.)')),
            ],
            options={
                'verbose_name_plural': 'Donors',
            },
        ),
        migrations.DeleteModel(
            name='FinancialInfo',
        ),
    ]
