# Generated by Django 4.2.5 on 2023-09-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0025_blooddonation_component_path_category_path_parameter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodDonation',
        ),
    ]
