# Generated by Django 4.2.5 on 2023-09-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0027_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module_Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.CharField(max_length=100)),
                ('appointment', models.BooleanField(default=False)),
                ('opd', models.BooleanField(default=False)),
                ('ipd', models.BooleanField(default=False)),
                ('pathology', models.BooleanField(default=False)),
                ('radiology', models.BooleanField(default=False)),
                ('blood_bank', models.BooleanField(default=False)),
                ('ambulance', models.BooleanField(default=False)),
            ],
        ),
    ]
