# Generated by Django 4.2.5 on 2023-09-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0030_pathology_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathology_test',
            name='amount',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pathology_test',
            name='standard_charge',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pathology_test',
            name='tax_percentage',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
