# Generated by Django 4.2.5 on 2023-09-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0032_pathology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathology',
            name='amount',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='tax_percentage',
            field=models.IntegerField(max_length=10),
        ),
    ]
