# Generated by Django 4.2.5 on 2023-09-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0033_alter_pathology_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathology',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='net_amount',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='payment_amount',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
