# Generated by Django 4.2.5 on 2023-09-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0034_alter_pathology_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdpatient',
            name='patient',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='discount',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='discount_percentage',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='tax',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='total',
            field=models.IntegerField(max_length=10),
        ),
    ]
