# Generated by Django 4.2.5 on 2023-09-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0035_ipdpatient_patient_alter_pathology_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdpatient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
