# Generated by Django 4.2.5 on 2023-09-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0036_alter_ipdpatient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('dose_interval', models.CharField(max_length=255)),
                ('dose_duration', models.CharField(max_length=255)),
                ('instruction', models.CharField(max_length=255)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.medicine')),
            ],
        ),
    ]
