# Generated by Django 4.2.5 on 2023-09-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0039_expensehead_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document', models.FileField(blank=True, null=True, upload_to='expense_documents/')),
                ('description', models.TextField()),
            ],
        ),
    ]
