# Generated by Django 4.2.5 on 2023-09-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0040_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('contact_person_name', models.CharField(max_length=100)),
                ('contact_person_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
