# Generated by Django 4.2.5 on 2023-09-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0042_childbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeathRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20)),
                ('patient_name', models.CharField(max_length=100)),
                ('death_date', models.DateField()),
                ('guardian_name', models.CharField(max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='death_attachments/')),
                ('report', models.TextField()),
            ],
        ),
    ]
