# Generated by Django 4.2.5 on 2023-09-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0044_referralcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_name', models.CharField(max_length=255)),
                ('referrer_contact', models.CharField(max_length=255)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_person_phone', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=255)),
                ('standard_commission', models.DecimalField(decimal_places=2, max_digits=5)),
                ('address', models.TextField()),
                ('commission_opd', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commission_ipd', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commission_pharmacy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commission_pathology', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commission_radiology', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commission_blood_bank', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commission_ambulance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
