# Generated by Django 4.2.5 on 2023-09-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0047_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
