# Generated by Django 4.2.5 on 2023-09-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0048_payment_patient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Referral',
        ),
    ]
