# Generated by Django 4.2.5 on 2023-09-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0049_rename_payment_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_model', models.CharField(max_length=255)),
                ('year_made', models.IntegerField()),
                ('driver_name', models.CharField(max_length=255)),
                ('driver_license', models.CharField(max_length=20)),
                ('driver_contact', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
