# Generated by Django 4.2.5 on 2023-09-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0050_ambulance'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_ambulancecall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('charge_category', models.CharField(max_length=100)),
                ('charge_name', models.CharField(max_length=100)),
                ('standard_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField()),
                ('total', models.IntegerField(max_length=10)),
                ('tax', models.IntegerField(max_length=10)),
                ('net_amount', models.IntegerField(max_length=10)),
                ('payment_mode', models.CharField(max_length=255)),
                ('payment_amount', models.IntegerField(max_length=10)),
            ],
        ),
    ]
