# Generated by Django 4.2.5 on 2023-09-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0052_itemcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('stock_code', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
