# Generated by Django 4.2.5 on 2023-09-26 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0055_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemcategory')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.supplier')),
            ],
        ),
    ]
