# Generated by Django 4.2.5 on 2023-09-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0057_alter_itemstock_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstock',
            name='store',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='supplier',
            field=models.CharField(max_length=100),
        ),
    ]
