# Generated by Django 4.2.5 on 2023-09-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0058_alter_itemstock_store_alter_itemstock_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path_category',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='path_category',
            name='unit',
        ),
        migrations.AddField(
            model_name='path_category',
            name='name',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
