# Generated by Django 4.2.5 on 2023-09-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0060_remove_path_parameter_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path_parameter',
            name='parameter_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='path_parameter',
            name='reference_range',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='path_parameter',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
