# Generated by Django 4.2.5 on 2023-09-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0061_alter_path_parameter_parameter_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radiology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('report_days', models.PositiveIntegerField()),
                ('report_date', models.DateField()),
                ('tax_percentage', models.IntegerField(max_length=10)),
                ('amount', models.IntegerField(max_length=10)),
                ('referral_doctor', models.CharField(max_length=255)),
                ('total', models.IntegerField(max_length=10)),
                ('discount_percentage', models.IntegerField(max_length=10)),
                ('discount', models.IntegerField(max_length=10)),
                ('tax', models.IntegerField(max_length=10)),
                ('net_amount', models.IntegerField(max_length=10)),
                ('payment_mode', models.CharField(max_length=255)),
                ('payment_amount', models.IntegerField(max_length=10)),
                ('note', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pathology',
            name='payment_mode',
            field=models.CharField(max_length=255),
        ),
    ]
