# Generated by Django 4.2.5 on 2023-09-27 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0062_radiology_alter_pathology_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiology',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.patient'),
        ),
    ]
