# Generated by Django 4.2.5 on 2023-09-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0063_radiology_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radiology_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('test_type', models.CharField(blank=True, max_length=100, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('report_days', models.PositiveIntegerField(default=0)),
                ('charge_category', models.CharField(blank=True, max_length=100, null=True)),
                ('charge_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_percentage', models.IntegerField(blank=True, max_length=5, null=True)),
                ('standard_charge', models.IntegerField(max_length=10)),
                ('amount', models.IntegerField(max_length=10)),
                ('test_parameter_name', models.CharField(max_length=100)),
                ('reference_range', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
    ]
