# Generated by Django 4.2.5 on 2023-09-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0064_radiology_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radio_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=255)),
            ],
        ),
    ]
