# Generated by Django 4.2.5 on 2023-09-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0065_radio_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radio_Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255, null=True)),
                ('reference_range', models.CharField(max_length=255, null=True)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
