# Generated by Django 4.2.5 on 2023-09-28 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0066_radio_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathology',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.patient'),
        ),
    ]
