# Generated by Django 4.2.5 on 2023-09-28 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0069_alter_ipdpatient_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdpatient',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.patient'),
        ),
    ]
