# Generated by Django 4.2.5 on 2023-09-28 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0070_alter_ipdpatient_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpdPatients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bp', models.CharField(max_length=20)),
                ('pulse', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('respiration', models.IntegerField()),
                ('symptoms_type', models.CharField(max_length=255)),
                ('symptoms_title', models.CharField(max_length=255)),
                ('symptoms_description', models.CharField(max_length=255)),
                ('admission_date', models.DateTimeField()),
                ('is_case_casualty', models.BooleanField()),
                ('is_old_patient', models.BooleanField()),
                ('is_tpa', models.BooleanField()),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=255)),
                ('consultant_doctor', models.CharField(max_length=255)),
                ('bed_group', models.CharField(max_length=255)),
                ('bed_number', models.CharField(max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='IpdPatient',
        ),
    ]
