# Generated by Django 4.2.5 on 2023-09-28 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0071_ipdpatients_delete_ipdpatient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdpatients',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.patient'),
        ),
    ]
