# Generated by Django 4.2.5 on 2023-09-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0072_alter_ipdpatients_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdpatients',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
