# Generated by Django 4.2.5 on 2023-09-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0075_rename_ipdpatients_ipdpatient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_det',
            name='payment_mode',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='OpdPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bp', models.CharField(max_length=20)),
                ('pulse', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('respiration', models.IntegerField()),
                ('symptoms_type', models.CharField(max_length=255)),
                ('symptoms_title', models.CharField(max_length=255)),
                ('symptoms_description', models.CharField(max_length=255)),
                ('admission_date', models.DateTimeField()),
                ('is_case_casualty', models.BooleanField()),
                ('is_old_patient', models.BooleanField()),
                ('is_tpa', models.BooleanField()),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=255)),
                ('consultant_doctor', models.CharField(max_length=255)),
                ('charge_category', models.CharField(blank=True, max_length=100, null=True)),
                ('charge_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_percentage', models.IntegerField(blank=True, max_length=5, null=True)),
                ('standard_charge', models.IntegerField(max_length=10)),
                ('amount', models.IntegerField(max_length=100)),
                ('Applied_charges', models.IntegerField(max_length=100)),
                ('paid_amount', models.IntegerField(max_length=100)),
                ('note', models.TextField(null=True)),
                ('any_known', models.TextField(null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.patient')),
            ],
        ),
    ]
