# Generated by Django 4.2.5 on 2023-09-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0076_alter_donor_det_payment_mode_opdpatient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='standard_charge',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='charge',
            name='tax_percentage',
            field=models.CharField(max_length=5),
        ),
    ]
