# Generated by Django 4.2.5 on 2023-09-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0077_alter_charge_standard_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdpatient',
            name='any_known',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opdpatient',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
