# Generated by Django 4.2.5 on 2023-09-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0079_alter_purchase_med_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('batch_no', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('mrp', models.IntegerField(max_length=20)),
                ('batch_amount', models.IntegerField(blank=True, max_length=20, null=True)),
                ('sale_price', models.IntegerField(max_length=10)),
                ('packing_qty', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.IntegerField(max_length=20)),
                ('tax_percentage', models.IntegerField(max_length=20)),
                ('amount', models.IntegerField(max_length=10)),
                ('documents', models.ImageField(blank=True, null=True, upload_to='medicine/')),
                ('note', models.TextField()),
                ('total', models.IntegerField(max_length=10)),
                ('discount_percentage', models.IntegerField(max_length=10)),
                ('discount', models.IntegerField(max_length=10)),
                ('tax', models.IntegerField(max_length=10)),
                ('net_amount', models.IntegerField(max_length=10)),
                ('payment_mode', models.CharField(max_length=255)),
                ('payment_amount', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Purchase_Med',
        ),
    ]
