# Generated by Django 4.2.5 on 2023-09-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0087_rename_nurse_doctornote_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor_det',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='donor_det',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='donor_det',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='donor_det',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='donor_det',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='donor_det',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='donor_det',
            name='total',
        ),
    ]
