# Generated by Django 4.2.5 on 2023-09-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0088_remove_donor_det_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonation_component',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='blooddonation_component',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='blooddonation_component',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='blooddonation_component',
            name='payment_mode',
        ),
    ]
