# Generated by Django 4.2.5 on 2023-09-29 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0089_remove_blooddonation_component_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation_component',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.patient'),
        ),
    ]
