# Generated by Django 4.2.5 on 2023-09-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0090_blooddonation_component_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donate_date', models.DateField()),
                ('bag', models.CharField(max_length=50)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit_type', models.CharField(max_length=50)),
                ('lot', models.CharField(max_length=50)),
                ('charge_category', models.CharField(max_length=100)),
                ('charge_name', models.CharField(max_length=100)),
                ('standard_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('institution', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('total', models.IntegerField(max_length=10)),
                ('discount_percentage', models.IntegerField(max_length=10)),
                ('discount', models.IntegerField(max_length=10)),
                ('tax', models.IntegerField(max_length=10)),
                ('net_amount', models.IntegerField(max_length=10)),
                ('payment_mode', models.CharField(max_length=255)),
                ('payment_amount', models.IntegerField(max_length=10)),
            ],
        ),
    ]
