# Generated by Django 4.2.5 on 2023-09-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0093_tax_cat_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax_cat',
            name='percentage',
            field=models.IntegerField(default=12, max_length=100),
        ),
    ]
