# Generated by Django 4.2.5 on 2023-10-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0095_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral_commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('standard_commission', models.IntegerField(max_length=10)),
                ('commission_opd', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('commission_ipd', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('commission_pharmacy', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('commission_pathology', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('commission_radiology', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('commission_blood_bank', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('commission_ambulance', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
        ),
    ]
