# Generated by Django 4.2.5 on 2023-10-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0096_referral_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstaff',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='staff_photos/'),
        ),
    ]
