# Generated by Django 4.2.5 on 2023-10-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0098_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.addstaff')),
            ],
        ),
    ]
