# Generated by Django 4.2.5 on 2023-10-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0099_salary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salary',
            new_name='Payroll',
        ),
        migrations.RenameField(
            model_name='addstaff',
            old_name='payroll',
            new_name='payroll_new',
        ),
    ]
