# Generated by Django 4.2.5 on 2023-10-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0101_alter_payroll_deduction_alter_payroll_earning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meeting_date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('host_video', models.BooleanField(default=True)),
                ('client_video', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('staff_list', models.TextField()),
            ],
        ),
    ]
