# Generated by Django 4.2.5 on 2023-10-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0102_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='min_level',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='reorder_level',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
    ]
