# Generated by Django 4.2.5 on 2023-10-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0103_alter_medicine_min_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gst_type', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=254)),
                ('billing_address', models.TextField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('as_of_date', models.DateField()),
                ('to_pay', models.BooleanField(default=False)),
                ('to_receive', models.BooleanField(default=False)),
            ],
        ),
    ]
