# Generated by Django 4.2.5 on 2023-10-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0104_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='opening_balance',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
    ]
