# Generated by Django 4.2.5 on 2023-10-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0106_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('invoice_number', models.CharField(max_length=10)),
                ('invoice_date', models.DateField()),
                ('state_of_supply', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('without_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('sale_price', models.DecimalField(decimal_places=3, max_digits=13)),
                ('disc_on_sale_price', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('purchase_price', models.DecimalField(decimal_places=3, max_digits=13)),
                ('tax_rate', models.DecimalField(decimal_places=3, max_digits=13)),
                ('opening_quantity', models.DecimalField(decimal_places=3, max_digits=13)),
                ('at_price', models.DecimalField(decimal_places=3, max_digits=13)),
                ('as_of_date', models.DateField()),
                ('min_stock_to_maintain', models.DecimalField(decimal_places=3, max_digits=13)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
