# Generated by Django 4.2.5 on 2023-10-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0109_item_acc_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('invoice_number', models.CharField(max_length=10)),
                ('invoice_date', models.DateField()),
                ('state_of_supply', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=13)),
                ('unit', models.CharField(max_length=13)),
                ('price_per_unit', models.DecimalField(decimal_places=3, max_digits=13)),
                ('without_tax', models.DecimalField(decimal_places=2, max_digits=13)),
                ('discount', models.DecimalField(decimal_places=3, max_digits=13)),
                ('discount_amount', models.DecimalField(decimal_places=3, max_digits=13)),
                ('tax', models.DecimalField(decimal_places=3, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total', models.DecimalField(decimal_places=3, max_digits=13)),
            ],
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
