# Generated by Django 4.2.5 on 2023-10-07 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0110_sales_invoice_delete_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_invoice',
            old_name='price_per_unit',
            new_name='price',
        ),
    ]
