# Generated by Django 4.2.5 on 2023-10-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0111_rename_price_per_unit_sales_invoice_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_invoice',
            name='without_tax',
        ),
    ]
