# Generated by Django 4.2.5 on 2023-10-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0113_remove_sales_invoice_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_invoice',
            name='type',
            field=models.CharField(default='sales', max_length=100),
        ),
    ]
