# Generated by Django 4.2.5 on 2023-10-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0114_sales_invoice_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=13)),
                ('asset_type', models.CharField(choices=[('Long-Term', 'Long-Term'), ('Short-Term', 'Short-Term')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='ipdpatient',
            name='respiration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipdpatient',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
