# Generated by Django 4.2.5 on 2023-10-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0115_asset_alter_ipdpatient_respiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(max_length=20),
        ),
    ]
