# Generated by Django 4.2.5 on 2023-10-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0117_medicationdoseage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField()),
                ('instruction_date', models.DateField()),
                ('consultant_doctor', models.CharField(max_length=100)),
                ('instruction', models.TextField()),
            ],
        ),
    ]
