# Generated by Django 4.2.5 on 2023-10-12 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0118_consultant_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant_register',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.patient'),
        ),
    ]
