# Generated by Django 4.2.5 on 2023-10-12 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0119_consultant_register_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_category', models.CharField(max_length=50)),
                ('operation_name', models.CharField(max_length=100)),
                ('operation_date', models.DateField()),
                ('consultant_doctor', models.CharField(max_length=100)),
                ('assistant', models.CharField(max_length=50, null=True)),
                ('assistant2', models.CharField(max_length=50, null=True)),
                ('anesthesia_type', models.CharField(blank=True, max_length=100)),
                ('ot_technician', models.CharField(blank=True, max_length=100)),
                ('ot_assistant', models.CharField(blank=True, max_length=100)),
                ('remark', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.patient')),
            ],
        ),
    ]
