# Generated by Django 4.2.5 on 2023-10-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0120_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipd_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(max_length=10)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
