# Generated by Django 4.2.5 on 2023-10-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0122_ipd_payments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ipd_Payment',
        ),
    ]
