# Generated by Django 4.2.5 on 2023-10-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0123_delete_ipd_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstaff',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=13, null=True),
        ),
    ]
