# Generated by Django 4.2.5 on 2023-10-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0124_alter_addstaff_basic_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstaff',
            name='basic_salary',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
