# Generated by Django 4.2.5 on 2023-10-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0125_alter_addstaff_basic_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstaff',
            name='number_of_leaves',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
