# Generated by Django 4.2.5 on 2023-10-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0126_alter_addstaff_number_of_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstaff',
            name='basic_salary',
            field=models.IntegerField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
