# Generated by Django 4.2.5 on 2023-10-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0127_alter_addstaff_basic_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_invoice',
            name='balance',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='total',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
    ]
