# Generated by Django 4.2.6 on 2023-10-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0128_sales_invoice_balance_sales_invoice_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_category', models.CharField(max_length=100)),
            ],
        ),
    ]
