# Generated by Django 4.2.6 on 2023-10-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0129_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_Categor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_category', models.CharField(max_length=100)),
                ('expense_type', models.CharField(max_length=20)),
            ],
        ),
    ]
