# Generated by Django 4.2.6 on 2023-10-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0130_expense_categor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense_Category',
        ),
    ]
