# Generated by Django 4.2.6 on 2023-10-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0131_delete_expense_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense_Categor',
            new_name='Expense_Category',
        ),
    ]
