# Generated by Django 4.2.5 on 2023-10-14 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0132_rename_expense_categor_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=3, max_digits=13)),
                ('tax', models.DecimalField(decimal_places=3, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Expense_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=10)),
                ('invoice_date', models.DateField()),
                ('balance', models.IntegerField(blank=True, max_length=20, null=True)),
                ('total', models.DecimalField(decimal_places=3, max_digits=13, null=True)),
                ('payment_type', models.CharField(max_length=20)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.expense_category')),
            ],
        ),
        migrations.CreateModel(
            name='Expense_inv_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=13)),
                ('unit', models.CharField(max_length=13)),
                ('price', models.DecimalField(decimal_places=3, max_digits=13)),
                ('total', models.DecimalField(decimal_places=3, max_digits=13)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.expense_invoice')),
            ],
        ),
    ]
