# Generated by Django 4.2.5 on 2023-10-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0133_expense_item_expense_invoice_expense_inv_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_invoice',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
