# Generated by Django 4.2.5 on 2023-10-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0134_sales_invoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_invoice',
            name='advance_amount',
            field=models.CharField(default=True, max_length=20, null=True),
        ),
    ]
