# Generated by Django 4.2.5 on 2023-10-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0135_sales_invoice_advance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_invoice',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
