# Generated by Django 4.2.5 on 2023-10-15 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0136_alter_sales_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_invoice',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
