# Generated by Django 4.2.5 on 2023-10-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0137_alter_sales_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_invoice',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
