# Generated by Django 4.2.5 on 2023-10-15 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0138_alter_sales_invoice_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_invoice',
            name='due_date',
        ),
    ]
