# Generated by Django 4.2.5 on 2023-10-15 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0139_remove_sales_invoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_invoice',
            name='due_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
