# Generated by Django 4.2.5 on 2023-10-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0141_alter_sales_invoice_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_In',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=50)),
                ('receipt_no', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('received', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
