# Generated by Django 4.2.5 on 2023-10-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0142_payment_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_invoice',
            name='payment_type',
            field=models.CharField(default='cash', max_length=100),
        ),
    ]
