# Generated by Django 4.2.5 on 2023-10-15 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0146_delete_bankaccount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankAccounts',
            new_name='BankAccount',
        ),
    ]
