# Generated by Django 4.2.5 on 2023-10-16 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0148_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_in',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.party'),
        ),
    ]
