# Generated by Django 4.2.5 on 2023-10-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0149_alter_payment_in_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_in',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
