# Generated by Django 4.2.5 on 2023-10-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0151_smtpserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Hospital Name', max_length=20)),
                ('image', models.ImageField(upload_to='cms')),
            ],
        ),
    ]
