# Generated by Django 4.2.5 on 2023-10-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0154_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
