# Generated by Django 4.2.5 on 2023-10-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0158_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
