# Generated by Django 4.1.2 on 2023-10-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0160_rename_room_messages_receiver_chatmessages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
