# Generated by Django 4.1.2 on 2023-11-08 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0162_alter_addstaff_photo_wallet_transactions_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_acc',
            name='sale_price',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet_transactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
