# Generated by Django 4.1.2 on 2023-11-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0163_alter_item_acc_sale_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liablity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=13)),
                ('liablity_type', models.CharField(max_length=20)),
            ],
        ),
    ]
