# Generated by Django 4.1.2 on 2023-11-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0165_alter_purchase_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Age',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
