# Generated by Django 4.1.2 on 2023-11-13 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0166_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathrecord',
            name='patient_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.patient'),
        ),
    ]
