# Generated by Django 4.1.2 on 2023-11-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0167_alter_deathrecord_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdpatient',
            name='discharged_status',
            field=models.BooleanField(default=False),
        ),
    ]
