# Generated by Django 4.1.2 on 2023-11-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0168_ipdpatient_discharged_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdpatient',
            name='discharged',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
