# Generated by Django 4.1.2 on 2023-11-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0169_ipdpatient_discharged'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdpatient',
            name='discharged',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='discharged_status',
            field=models.BooleanField(default=False),
        ),
    ]
