# Generated by Django 4.2.6 on 2023-11-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0170_opdpatient_discharged_opdpatient_discharged_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precreption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_category', models.CharField(max_length=255)),
                ('findings', models.CharField(max_length=15)),
                ('finding_description', models.TextField()),
                ('doctor', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='referral',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.patient'),
        ),
        migrations.CreateModel(
            name='Precreption_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_category', models.CharField(max_length=255)),
                ('medicine', models.CharField(max_length=20)),
                ('dosage', models.CharField(max_length=13)),
                ('does_interval', models.CharField(max_length=15)),
                ('dose_duration', models.CharField(max_length=15)),
                ('instruction', models.TextField(null=True)),
                ('pres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.precreption')),
            ],
        ),
    ]
