# Generated by Django 4.2.6 on 2023-11-16 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0171_precreption_alter_referral_patient_precreption_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='precreption',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.patient'),
        ),
    ]
