# Generated by Django 4.1.2 on 2023-11-16 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0172_precreption_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='donor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.donor_det'),
        ),
    ]
