# Generated by Django 4.1.2 on 2023-11-17 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0173_alter_blooddonation_donor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='donor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.donor_det'),
        ),
    ]
