# Generated by Django 4.1.2 on 2023-11-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0174_alter_blooddonation_donor_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor_det',
            options={},
        ),
        migrations.AlterField(
            model_name='donor_det',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor_det',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='donor_det',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='donor_det',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donor_det',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
