# Generated by Django 4.1.2 on 2023-11-20 18:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0177_payroll_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathology',
            name='test_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.pathology_test'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date',
            field=models.DateField(default=datetime.date(2023, 11, 20)),
        ),
    ]
