# Generated by Django 4.1.2 on 2023-11-21 00:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0178_alter_pathology_test_name_alter_payroll_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='date',
            field=models.DateField(default=datetime.date(2023, 11, 21)),
        ),
        migrations.AlterField(
            model_name='radiology',
            name='test_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.radiology_test'),
        ),
    ]
