# Generated by Django 4.1.2 on 2023-11-22 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0181_alter_radiology_test_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('id_card', models.CharField(max_length=20)),
                ('visit_to', models.CharField(max_length=10)),
                ('patient', models.CharField(max_length=10)),
                ('num_of_person', models.IntegerField()),
                ('date', models.DateField()),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('note', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='static/visitors')),
            ],
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date',
            field=models.DateField(default=datetime.date(2023, 11, 22)),
        ),
    ]
