# Generated by Django 4.1.2 on 2023-11-22 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0183_postal_dispatch_postal_receive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date',
            field=models.DateField(default=datetime.date(2023, 11, 23)),
        ),
        migrations.AlterField(
            model_name='postal_dispatch',
            name='attach_document',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
    ]
