# Generated by Django 4.1.2 on 2023-11-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0185_complain_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_type', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('complain_by', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('action_taken', models.TextField()),
                ('assigned', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('attach_document', models.FileField(blank=True, null=True, upload_to='static/complain')),
            ],
        ),
    ]
