# Generated by Django 4.1.2 on 2023-11-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0189_alter_payroll_date_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
