# Generated by Django 4.1.2 on 2023-11-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0190_medicine_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='price',
        ),
    ]
