# Generated by Django 4.1.2 on 2023-11-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0191_remove_medicine_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.purchase'),
        ),
    ]
