# Generated by Django 4.1.2 on 2023-11-26 10:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0192_alter_stock_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=20)),
                ('payment_mode', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('composition', models.CharField(max_length=20)),
                ('small_note', models.CharField(max_length=20)),
                ('tax_percent', models.DecimalField(decimal_places=3, max_digits=13)),
                ('discount_percent', models.DecimalField(decimal_places=3, max_digits=13)),
                ('net_amount', models.DecimalField(decimal_places=3, max_digits=13)),
            ],
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date',
            field=models.DateField(default=datetime.date(2023, 11, 26)),
        ),
        migrations.CreateModel(
            name='Pos_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=13)),
                ('batch_no', models.CharField(max_length=13)),
                ('expiry_date', models.DecimalField(decimal_places=3, max_digits=13)),
                ('price', models.DecimalField(decimal_places=3, max_digits=13)),
                ('tax', models.DecimalField(decimal_places=3, max_digits=13)),
                ('total', models.DecimalField(decimal_places=3, max_digits=13)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.sales_invoice')),
            ],
        ),
    ]
