# Generated by Django 4.1.2 on 2023-11-28 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0194_operation_assistants_delete_pos_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='assistant',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='assistant2',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date',
            field=models.DateField(default=datetime.date(2023, 11, 29)),
        ),
    ]
