# Generated by Django 4.2.6 on 2023-11-30 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0196_alter_payroll_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_invoice',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
