# Generated by Django 4.2.6 on 2023-11-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0197_alter_sales_invoice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_invoice',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
    