# Generated by Django 4.2.6 on 2023-11-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0198_alter_sales_invoice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathology_test',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
