# Generated by Django 4.1.2 on 2023-11-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0200_cashbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='balance',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='credit',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='debit',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='lf',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='particulars',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
