# Generated by Django 4.1.2 on 2023-11-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0201_cashbook_balance_cashbook_credit_cashbook_debit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine_Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
