# Generated by Django 4.1.2 on 2023-11-30 19:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0202_medicine_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='composition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.medicine_composition'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 1)),
        ),
    ]
