# Generated by Django 4.1.2 on 2023-12-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0204_bankbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(max_length=20)),
                ('balance', models.IntegerField(max_length=20)),
                ('amount', models.IntegerField(max_length=20)),
            ],
        ),
    ]
