# Generated by Django 4.1.2 on 2023-12-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0206_pos_batch_no_pos_category_pos_expiry_date_pos_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brs',
            name='operation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
