# Generated by Django 4.1.2 on 2023-12-01 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0207_brs_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('ac', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 2)),
        ),
    ]
