# Generated by Django 4.1.2 on 2023-12-01 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0208_bank_alter_payroll_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbook',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.bank'),
        ),
    ]
