# Generated by Django 4.1.2 on 2023-12-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0209_bankbook_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='account_no',
            field=models.IntegerField(max_length=30, null=True),
        ),
    ]
