# Generated by Django 4.1.2 on 2023-12-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0212_brs_adjusted_alter_payroll_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brs',
            name='adjusted',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
    ]
