# Generated by Django 4.1.2 on 2023-12-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0216_alter_asset_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciation',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
