# Generated by Django 4.1.2 on 2023-12-04 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0217_alter_depreciation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Blood_Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=20)),
                ('bag', models.CharField(max_length=20)),
                ('volume', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('lot', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=20)),
                ('component_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.blood_setup')),
            ],
        ),
    ]
