# Generated by Django 4.1.2 on 2023-12-08 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0220_alter_leaves_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 8)),
        ),
    ]
