# Generated by Django 4.2.6 on 2023-12-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0221_alter_payroll_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag_available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(max_length=10)),
            ],
        ),
    ]
