# Generated by Django 4.2.6 on 2023-12-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0222_bag_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='composition',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
