# Generated by Django 4.1.2 on 2023-12-13 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0223_alter_pos_composition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 14)),
        ),
        migrations.AlterField(
            model_name='pos',
            name='discount_percent',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='pos',
            name='doctor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pos',
            name='net_amount',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='pos',
            name='payment_mode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pos',
            name='small_note',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pos',
            name='tax_percent',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
    ]
