# Generated by Django 4.1.2 on 2023-12-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0224_alter_payroll_date_alter_pos_discount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('attendance', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('note', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.addstaff')),
            ],
        ),
    ]
