# Generated by Django 4.1.2 on 2023-12-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0226_alter_payroll_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
