# Generated by Django 4.1.2 on 2023-12-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0227_attendance_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('attendance', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
