# Generated by Django 4.1.2 on 2023-12-24 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0228_other_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdpatient',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 24)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 24)),
        ),
    ]
