# Generated by Django 4.1.2 on 2023-12-24 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0229_ipdpatient_date_alter_payroll_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdpatient',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 24)),
        ),
    ]
