# Generated by Django 4.1.2 on 2023-12-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0230_opdpatient_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.DecimalField(decimal_places=3, max_digits=13)),
                ('total_purchases', models.DecimalField(decimal_places=3, max_digits=13)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=13)),
                ('opening_stock', models.DecimalField(decimal_places=3, max_digits=13)),
                ('closing_stock', models.DecimalField(decimal_places=3, max_digits=13)),
                ('total_sales_tax', models.DecimalField(decimal_places=3, max_digits=13)),
                ('total_short_term_assets', models.DecimalField(decimal_places=3, max_digits=13)),
                ('total_long_term_liability', models.DecimalField(decimal_places=3, max_digits=13)),
                ('total_short_term_liability', models.DecimalField(decimal_places=3, max_digits=13)),
                ('total_long_term_assets', models.DecimalField(decimal_places=3, max_digits=13)),
                ('total_purchase_tax', models.DecimalField(decimal_places=3, max_digits=13)),
                ('start_date', models.DateField()),
                ('receivable', models.DecimalField(decimal_places=3, max_digits=13)),
                ('payable', models.DecimalField(decimal_places=3, max_digits=13)),
                ('indirect_expense', models.DecimalField(decimal_places=3, max_digits=13)),
                ('direct_expense', models.DecimalField(decimal_places=3, max_digits=13)),
                ('withdraw', models.DecimalField(decimal_places=3, max_digits=13)),
                ('equity', models.DecimalField(decimal_places=3, max_digits=13)),
                ('other_income', models.DecimalField(decimal_places=3, max_digits=13)),
            ],
        ),
    ]
