# Generated by Django 4.1.2 on 2023-12-24 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0231_balancesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdpatient',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 25)),
        ),
        migrations.AlterField(
            model_name='opdpatient',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 25)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 25)),
        ),
    ]
