# Generated by Django 4.1.2 on 2024-01-07 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0232_alter_ipdpatient_date_alter_opdpatient_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20)),
                ('phone_no', models.IntegerField(max_length=20, null=True)),
                ('email_id', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ipdpatient',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 7)),
        ),
        migrations.AlterField(
            model_name='opdpatient',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 7)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 7)),
        ),
    ]
