# Generated by Django 4.1.2 on 2024-01-23 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0234_alter_ipdpatient_date_alter_opdpatient_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdpatient',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 24)),
        ),
        migrations.AlterField(
            model_name='opdpatient',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 24)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 24)),
        ),
    ]
