# Generated by Django 4.1.2 on 2024-01-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0235_alter_ipdpatient_date_alter_opdpatient_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
