# Generated by Django 4.1.2 on 2024-01-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0236_alter_visitors_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
