# Generated by Django 4.1.2 on 2024-01-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0238_alter_visitors_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cause_of_emergebcy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='gardian_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gardian_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gardian_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tpa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
